### ISSUE TITLE
Undefined symbols for architecture … FGuidReferences …  in Module.GASAssociate.gen.cpp.o

### ISSUE THREAD

**Issue by timoxley** [archangel4031/GASAssociate#1]
Trying to build using 5.0 release on an M1 Mac via VSCode:
```
Undefined symbols for architecture x86_64:
  "FGuidReferences::~FGuidReferences()", referenced from:
      TSparseArray<TSetElement<TTuple<int, FGuidReferences> >, TSparseArrayAllocator<TSizedDefaultAllocator<32>, FDefaultBitArrayAllocator> >::Empty(int) in Module.GASAssociate.gen.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any ideas?

**Comment by archangel4031** [comment]
These gen.cpp files are generated by the Unreal Header Tool. Maybe something got corrupted for some reason. Try to delete the Binaries and Intermediate folders from project root directory. Then go into Plugins folder and delete these same folders from each plugin. Finally right click on .uproject file and select Generate Visual Studio Project files. Try to compile from IDE before opening the engine.

**Comment by dkalinaUWE** [comment]
> Trying to build using 5.0 release on an M1 Mac via VSCode:
> 
> ```
> Undefined symbols for architecture x86_64:
>   "FGuidReferences::~FGuidReferences()", referenced from:
>       TSparseArray<TSetElement<TTuple<int, FGuidReferences> >, TSparseArrayAllocator<TSizedDefaultAllocator<32>, FDefaultBitArrayAllocator> >::Empty(int) in Module.GASAssociate.gen.cpp.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> Any ideas?

@timoxley I'm seeing the same linker error trying to build a project - did you ever resolve this?  Thanks in advance!

**Comment by archangel4031** [comment]
Seems like this issue is still present on Mac. Unfortunately, I do not have a Mac with me to test this issue. Did you try my method that I mentioned above? Maybe this article would help https://forums.unrealengine.com/t/solved-plugin-error-undefined-symbols-for-architecture-x86_64-private-folders/120198/3

I'm reopening the issue until someone confirms that this can be resolved

**Comment by JeremyGeros** [comment]
Hi, I was having a similar issue on my own GAS project and trying to build on mac. I solved it by adding `"NetCore"` to the  PublicDependencyModuleNames array in the Build.cs file in my project.

**Comment by davekalina** [comment]
@JeremyGeros Adding NetCore to my build script fixed the problem.  Thank you!

**Comment by timoxley** [comment]
@archangel4031 maybe worth updating the readme?

**Comment by archangel4031** [comment]
@timoxley Done. Thanks for the suggestion!

**Comment by benflightpro** [comment]
Adding NetCore does not help.

**Comment by benflightpro** [comment]
also getting a warning for:
/Users/benflight/Documents/Unreal Projects/MyProject2/Plugins/GASAssociateHelper/Source/GASAssociateHelper/Private/GASAssociateHelperCommands.cpp:9:120: 'FInputGesture' is deprecated: Use FInputChord instead of FInputGesture Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.

But failing on:
Undefined symbols for architecture x86_64:
  "FGuidReferences::~FGuidReferences()", referenced from:
      TSparseArray<TSetElement<TTuple<int, FGuidReferences> >, TSparseArrayAllocator<TSizedDefaultAllocator<32>, FDefaultBitArrayAllocator> >::Empty(int) in Module.GASAssociate.gen.cpp.o
[13/14] Link UnrealEditor-GASAssociateHelper.dylib
Command /Users/Shared/Epic Games/UE_5.0/Engine/Build/BatchFiles/Mac/XcodeBuild.sh failed with exit code 6

**Comment by benflightpro** [comment]
Assuming the warning is related to the compiler error given that it straight up says it won't compile.

**Comment by archangel4031** [comment]
@benflightpro like I said, I do not have a Mac to test this plugin. It would be difficult for me to identify the cause of this issue. Adding `NetCore` should have solved the issue as it did for others.
However, can you try theses solutions and let me know if any one of these worked?
- https://forums.unrealengine.com/t/how-can-i-resolve-the-error-unparsed-class-script-kismet-blueprintpalettefavorites/278259#answer-32243
- https://forums.unrealengine.com/t/solved-plugin-error-undefined-symbols-for-architecture-x86_64-private-folders/120198/3

As for deprecation warning, I am waiting for 5.1 release to update the plugin.

**Comment by benflightpro** [comment]
Actually i think i figured it out. I was adding NetCore to the Build.cs for the project itself when i should have been adding it to each of the plugins.
